repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-merge-conflict
    - id: debug-statements
  
- repo: local

  hooks:
    - id: black
      name: black
      entry: black
      language: system
      types: [python]
      args: [--line-length=200, --target-version=py37]

    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
      args: ["--ignore=E501"]
      
    - id: mypy
      name: mypy
      entry: mypy
      language: system
      types: [python]
      
    - id: isort
      name: isort
      entry: isort
      language: system
      types: [python]
      
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
      
    #- id: autoflake
    #  name: autoflake
    #  entry: autoflake
    #  language: system
    #  types: [python]
    #  args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys]